#! /bin/bash

# Auto-load the environment, including .env.local
set -a
[ -f "$(dirname "$0")/.env.local" ] && source "$(dirname "$0")/.env.local"
source "$(dirname "$0")/.env"
set +a

# Bring down any deployed canaries
docker compose -f ./docker-compose-debug.yaml down

# Bring down the network core
docker compose -f ./docker-compose-traefik.yaml down